version: '3.8'

services:
  database:
    image: mariadb:10.4.4-bionic
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: staytus
      MYSQL_USER: staytus
      MYSQL_PASSWORD: staytus
    networks:
      - staytus

  staytus:
    image: quay.io/galexrt/staytus:latest
    container_name: staytus
    ports:
      - "8787:8787"
    environment:
      DB_HOST: database
      DB_USER: staytus
      DB_PASSWORD: staytus
    networks:
      - staytus

networks:
  staytus:
    driver: bridge
