---
all:
  hosts:
    server:
      ansible_host: 62.84.117.224
      ansible_user: ec2-user
      ansible_ssh_private_key_file: /Users/test/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
      local_ip: 10.250.240.36
    localhost:
      ansible_connection: "local"
    